### ISSUE TITLE
Unproject x and y from the Agent to lat and long in WGS84

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#1]
Right now the location is in a projected world, we need to be able to extract the lat and long in WGS 84 to send it to cityIO

**Comment by agrignard** [comment]
This operator is meant to do this opposite (from WGS 84 to CRS)
https://groups.google.com/forum/#!searchin/gama-platform/GAMA_CRS%7Csort:date/gama-platform/Uny5e3Vx7AI/mMnB2Pv8AgAJ

I am investing on how to do the opposite (from projected to wgs84)

**Comment by agrignard** [comment]
ok this should be the right line:
`````
location CRS_transform "EPSG:4326";
`````

then location will hopefully be in the WGS format (we need to test it)

**Comment by doorleyr** [comment]
Where do I put this line? Anywhere I put it, it gives an error: "location" seems to be incomplete

**Comment by agrignard** [comment]
````
location <-point(location CRS_transform "EPSG:4326");
````

**Comment by doorleyr** [comment]
Ok that works. Thanks.
https://github.com/CityScope/CS_Mobility_Service/commit/194132aee3afe39af828e29d9fbd528cf6ce5a54
