### ISSUE TITLE
Projection naming convention modification

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#14]
In link  to this issue https://groups.google.com/forum/#!topic/gama-platform/E2pkBa58DZQ

@doorleyr would you be ok (we have to be sure that it has no impact on your code) to make a slight modification in most of you geojson? I can make it I just want to be sure that it has no impact on your code 

In order to be able to read those file in GAMA we need to change this:

"urn:ogc:def:crs:OGC:1.3:CRS84"
by
"epsg:4326"

**Comment by doorleyr** [comment]
Fixed with 2d6d9ba

**Comment by agrignard** [comment]
thanks!
