### ISSUE TITLE
Mode value and type

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#15]
@doorleyr 

Can you remind me what is the corresponding mode 
0:? (car, bike,etc?)
1:?

Maybe this can be included in the wiki or in the readme?

**Comment by doorleyr** [comment]
Yeah I need to update the README so I'll put it there. Anyway, the modes are:
0: driving
1: cycling
2: walking
3: public transit

**Comment by agrignard** [comment]
Ok

**Comment by RELNO** [comment]
@agrignard @doorleyr do we have this documented somewhere? It might make sense to have an agreed format for this since (for example) the noise module also have different vehicle types for noise emission.

**Comment by doorleyr** [comment]
I now have it in the REAME
