### ISSUE TITLE
Network simplification

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#16]
The current network for different mobility mode are too complex to be usable in a "real-time" manner by GAMA. It would be great to have the minimal network that enables a light simulation but keeping the right granularity.  

Geojson networks for each mode can be found here:
https://github.com/CityScope/CS_Mobility_Service/blob/master/scripts/cities/Hamburg/clean/cycling_net.geojson
https://github.com/CityScope/CS_Mobility_Service/blob/master/scripts/cities/Hamburg/clean/walking_net.geojson
https://github.com/CityScope/CS_Mobility_Service/blob/master/scripts/cities/Hamburg/clean/driving_net.geojson
https://github.com/CityScope/CS_Mobility_Service/blob/master/scripts/cities/Hamburg/clean/pt_net.geojson

**Comment by doorleyr** [comment]
I significantly reduced the pedestrian and public transit networks (the driving and cycling networks are the same as before). Let me know if it's better now. Also, as discussed, you can try taking a sample of the agents that I post to cityIO (about 4000 agents I think).

**Comment by agrignard** [comment]
Great it s running much more smoother now (however I cannot push the result yet see https://github.com/CityScope/CS_Simulation_GAMA/issues/52)

**Comment by agrignard** [comment]
Well I was a but too optimistic. I think it it is still a bit too complex (more than 3000 segments are created) but let's keep lie that for now
