### ISSUE TITLE
Micro Mobility Modification for Hamburg footprint and single entry point

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#17]
- Change sim_area to the exact table footprint
https://github.com/CityScope/CS_Mobility_Service/blob/master/scripts/cities/Hamburg/raw/sim_area.geojson

See https://github.com/CityScope/CSL_Hamburg_Grasbrook

- Add a single entry point

**Comment by doorleyr** [comment]
Taking a closer look at this, I don't think having a single entry point will be best. If we do that, then all the agents will appear at the entrance to the site. However, there are roads within the table area that agents would have to travel on to reach that entry point. We should show the agents' route as soon as they enter the table area. To achieve this, I think we need to have 3 entry points, at the top-right middle-right and bottom-right of the table area.

**Comment by doorleyr** [comment]
Now ready for Grasbrook with the smaller region and 3 entry points. @agrignard can you test with your ABM?

**Comment by doorleyr** [comment]
This is now also ready for the Corktown site. Just use the Detroit folder for the data inputs and the corktown endpoint on cityIO and everything else should work the same.

**Comment by agrignard** [comment]
this current micro mobility service point on those file
``````
file JsonFile <- json_file("https://cityio.media.mit.edu/api/table/grasbrook/od");	
	file geo_file <- geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/Hamburg/clean/sim_area.geojson");
	
	file walk_network<-geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/Hamburg/clean/walking_net.geojson");
	file cycling_network<-geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/Hamburg/clean/cycling_net.geojson");
	file car_network<-geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/Hamburg/clean/driving_net.geojson");
	file pt_network<-geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/Hamburg/clean/pt_net.geojson");
``````

Where can I found the newest one (for the smaller simualtion area). I am not sure to get your point about the only entrance but we can even make the 2 version

**Comment by doorleyr** [comment]
I have a new geojson called table_area. I made some minor edits in 5642e27 to fix this. Also, you can now easily switch to Detroit by changing 'city' to Detroit.
