### ISSUE TITLE
Converge on json struct 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Mobility_Service#18]
Current POST looks a following:
![Screen Shot 2019-09-05 at 16 34 02](https://user-images.githubusercontent.com/14296774/64378663-2d952200-cffb-11e9-8c77-6d33d6028b29.png)
Should converge on [`trips`](https://cityio.media.mit.edu/api/table/grasbrook/trips
) (or any other agreed upon) format.

**Comment by agrignard** [comment]
I am ok for both. right now both are sending "mode"
https://cityio.media.mit.edu/api/table/grasbrook/cityIO_Gama_Hamburg
https://cityio.media.mit.edu/api/table/grasbrook/trips

https://github.com/CityScope/CS_Simulation_GAMA/commit/d18dca9cd7e60b49337acd5cc91879e0587f33ce

**Comment by doorleyr** [comment]
The one remaining difference is that in the GAMA data, the trips object is contained in another object i.e.

cityIO_Gama_Hamburg: {contents: trips_object}
trips: trips_object

I'm fine to change mine if we agree it makes more sense.

**Comment by RELNO** [comment]
Thanks -- I (deckGL) would prefer if @agrignard will converge to @doorleyr format. I cannot parse the `contents` attr. easily. `mode` works well for both

**Comment by agrignard** [comment]
Ok it is fixed. Just for the record I was using not the newest version of GAMA that's why there was those contents ( cf https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gama-dev/HiiWNdWniZM/5Rt_v7auEgAJ for the discussion about this)
