### ISSUE TITLE
Converge on time stamps 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Mobility_Service#19]
now, time is calc as the following: 

```
    let loopLength = 4 * 60 * 60;
    let animationSpeed = 50;
    const timestamp = Date.now() / 1000;
    const loopTime = loopLength / animationSpeed;
    let t = ((timestamp % loopTime) / loopTime) * loopLength;
    var mobilitySlider = document.getElementById("mobilitySlider").value;
    let time = t + (mobilitySlider / 100) * loopLength;
```

The two sims do not exactly correspond and I solve it with: 
@doorleyr : 
         ` currentTime: time`
@agrignard : 
        `  currentTime: time + 30000`

Let's decide we run the sim over 24hrs or, at the very least 5am to 1am. This will cover most cases/cities.

**Comment by doorleyr** [comment]
There should be just one Trips layer going forward (from CS_Simulation_GAMA) so closing this.

**Comment by agrignard** [comment]
Does it means there is no representation of time in the trip layer? It will be seen as an aggregated graph for the whole day?

**Comment by RELNO** [comment]
> Does it means there is no representation of time in the trip layer? It will be seen as an aggregated graph for the whole day?

The trip layer hasn't changed, and still has time stamps. I think @doorleyr meant we do not visualize his mobility layer under the same output format of deckgl trips layer.

**Comment by RELNO** [comment]
Looks like we're in agreement on 24hrs, 1 sec intervals. This discussion continues on frontend. Closing.
