### ISSUE TITLE
Adding Detroit City in the GAMA simulation

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#23]
Would be great to also have the GAMA ABM model running to detroit

https://github.com/CityScope/CS_Mobility_Service/tree/master/GAMA/includes

**Comment by doorleyr** [comment]
To get the Detroit ABM, you just have to change the 'city' variable to 'Detroit' in https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/MicroSimulationFromMacroMobilityModel.gaml

**Comment by agrignard** [comment]
Sorry I was speaking about the GAMA ABM model in this reposetory=> MoBalance.gaml model . I know this model is not the same and we don't use it anymore, however it is still coherent to keep the backward compatibility for people interested to run or modify it.

**Comment by agrignard** [comment]
What about this issue? It sounds a bit old no?

**Comment by agrignard** [comment]
I dont see any reference anymore to MoBlance.gaml in this repo I think this issue is clearly so 2019's ;-). I close it for now. 

Just in case the Gama model running with this repo can be found here https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/CityScope/MicroSimulationFromMacroMobilityModel.gaml
