### ISSUE TITLE
Very few people commuting to Grasbrook

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#24]
I am surprised by the very few amounts of people commuting to grasbrook, it used to be much more higher. Right now there is only 19 people. Is due to the current landuse where most of the area in Industrial?

See
`````
https://cityio.media.mit.edu/api/table/grasbrook/od
`````

**Comment by doorleyr** [comment]
That was due to a previous table state which had few active land uses. I ran my model again and there are more agents now.
