### ISSUE TITLE
Controling the amount of people spawn and the size of the network

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#27]
In order to have easy to replciate model it would be great to be able to control the number of agent and the size of the network

Right now there is a big difference in term of computaion of agentand with the road network  between Grassbrook and Detroit, which make it difficult to maintain (right now Corktown cannot work with the same settings as grassbrook)

Would it make sense to have a way to limit the number of agent and the number of roads?

**Comment by doorleyr** [comment]
Regarding the number of people, we could keep the number of agents constant. But wouldn't this affect some of the resulting metrics? eg. if density increases on a site, then things like interaction density should increase but if the number of agents is kept constant this may not happen.

As for the roads, I'm pretty sure we can't limit their number, right?

Which settings are you talking about? Maybe there's a way to change them dynamically based on the needs of the simulation?

**Comment by doorleyr** [comment]
Closing as there's no actions to take.
