### ISSUE TITLE
Push from GAMA to cityIO the list of agent

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#3]
The push to cityIo from GAMA is almost done for a grid and can be used as inspiration to send the agent position.

See https://github.com/CityScope/CS_CityIO_Backend/tree/master/examples/GAMA/cityIO_Gama

**Comment by agrignard** [comment]
In link with this issue
https://github.com/CityScope/CSL_Hamburg_Grasbrook_Angular_Prototype/issues/14

**Comment by agrignard** [comment]
Ok so this is a starting point:
https://cityio.media.mit.edu/api/table/grasbrook_sim

If we can extract the same Json from GAMA then we can direclty read it in the same way as the SUMO.

After we need to agree on a format a bit more standardized

**Comment by doorleyr** [comment]
Done. But cityIO is down at the moment so not fully tested yet. Will keep the issue open until it's tested.
https://github.com/CityScope/CS_Mobility_Service/commit/194132aee3afe39af828e29d9fbd528cf6ce5a54

**Comment by agrignard** [comment]
@doorleyr FYI I tried to send a GeoJson to CityIO right now it not possible (See https://github.com/CityScope/CS_CityIO_Backend/issues/67 )  as cityIO is waiting for a json compatible with the 2.1 format. This is still in discussion with @yasushisakai and @RELNO whether this information (the simulation one) should be sent directly to cityIO or through its own API (which required, in my opinion, much more work from the thrid part software)

**Comment by doorleyr** [comment]
Ok so for now (at least until Member's week) how about we keep the points data in the 'objects' field; that way it's compatible with cityIO format. We can continue the discussion about whether we need separate end-points over the next few weeks.
