### ISSUE TITLE
General Activity Simulation

### ISSUE THREAD

**Issue by wangcan1213** [CityScope/CS_Mobility_Service#30]
As a followup for general activity simulation, some modifications were made to abm.py in dev branch. It will process a person's activity schedule and finally yield OD objects with following attributes: when to start, when to stop, move from where to where by which mode, and which type of activity. Two predictions are needed: (1) place where the activity will happen, it is acquired by randomly choosing a grid with proper land use for that activity; (2) mode for moving towards the place, it is predicted by the former RF model.

While doing this I found following issues worth mentioning.
(1) It is difficult to find proper and specific land uses for certain activities. A better classification system for land uses shall help. 
(2) We'd better use a more realistic model than just randomly picking a relevant grid. A Huff-model might work, but behavioral data are needed to calibrate the parameters.
(3) Right now all activities are assumed to happen inside our simulation area, which is obviously not a ideal way. Actually it is almost impossible for some activities, as there is no medical POI and only one school in the area, according to OSM. 
(4) As to mode prediction, each OD is a totally independent case without considering some kind of consistency among multiple ODs for the same person. For instance, it is possible to get outcomes that a person walk from home to work, and then drive back to home.

**Comment by agrignard** [comment]
See also https://github.com/CityScope/cityscope.github.io/issues/15

**Comment by doorleyr** [comment]
@wangcan1213 thanks for this, I think we will use your code but I can't merge the branch to main yet. There's still some work to be done on determining the activity sequences and making sure we're all agreed on the general approach for dealing with activities and land uses.

regarding point 1, I think we're getting close to a solution for this in this issue: https://github.com/CityScope/cityscope.github.io/issues/15

Regarding point 2, it's unlikely we're going to be able to calibrate a Huff model. Do you know if there is a reasonable standard we can use for the exponent of distance. Perhaps we can just assume that probability of choosing a place decreases linearly or with the 2nd power of distance?

Regarding point 3, if there no possibility on the site we can either assume the person skips the desired activity or maybe goes outside the area (to a portal)

As to point 4, let's keep it this way for now. Later, we could maybe fit two mode choice models: one for main mode, and another for trip modes (which would use the main mode as an explanatory variable).

**Comment by doorleyr** [comment]
Resolved
