### ISSUE TITLE
github account

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#4]
@doorleyr would it be possible to use the correct github account when you push?

https://github.com/doorleyr

Right now the commit in this repo seems to be linked to another account which makes things a bit more complicated to follow the work

For example this https://github.com/CityScope/CS_Mobility_Service/commit/501ffa9a430ecf32d90865392d5d3b6602c49370 is commited by ````Ronan Doorley ``` instead of ````doorleyr````

**Comment by doorleyr** [comment]
There was an issue with my git config files so it was linked to another account. It's fixed now.
