### ISSUE TITLE
Missing files in scripts/cities/clean

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#41]
I use to run a GAMA mobility model which was taking ad input some data coming from this repo 
`````
file table_area_file <- geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/"+city+"/clean/table_area.geojson");
file walking_net_file<-geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/"+city+"/clean/walking_net.geojson");
file cycling_net_file<-geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/"+city+"/clean/cycling_net.geojson");
file driving_net_file<-geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/"+city+"/clean/driving_net.geojson");
file pt_net_file<-geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/"+city+"/clean/pt_net.geojson");
file portals_file<-geojson_file("https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/"+city+"/clean/portals.geojson");
`````

Some of them are still here like ```table_area.json``` but I cannot find the different network, @doorleyr did you move them somewhere else?

**Comment by doorleyr** [comment]
I had removed the geojson network files as they weren't being used but I added them back now.

**Comment by agrignard** [comment]
Great it's working again! Thank you

**Comment by agrignard** [comment]
We are working on the new version of GAMA I am trying to see and gather which CityScope project is still using GAMA or what needs to be archived or modify to make it compatible.

Juste went back in the log of this repo where we use to have a GAMA model plug to the random forest tree 

So just for documentation if needed it can be refound before this commit
https://github.com/CityScope/CS_Mobility_Service/commit/a1dabf98b5e803a88dce1c7e578bd24ea9bca7bb

I am wondering if this model could/should eventually leave in this repo (https://github.com/CityScope/CS_Simulation_GAMA/tree/master/CS_CityScope_GAMA) to facilitate the maintenance/backward compatibility of it.
