### ISSUE TITLE
Code readability

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Mobility_Service#6]
This list of parameter are not very clear for me and make the code pretty hard to understand, what abotu having a list for instance

``````
	int occat_1<-0;
	int occat_2<-0;
	int occat_3<-0;
	int occat_4<-0;
	int occat_5<-0;
``````

something like could save 5 lines and make it more generic (where the list coudl be of size n)

``````
list<int> occat <-[0,0,0,0,0];
``````

Could be the same for res_00

**Comment by doorleyr** [comment]
I tried doing it that way at first but I needed to include each these as parameters in the experiment. If I try to put eg.:
parameter "Sales jobs" var: occat[0] category: "New Jobs" min: 0 max: 50;
I get an error. So I instead declared each one as a separate parameter and then collected them into a list:

list nm_occats<-[occat_1, occat_2, occat_3, occat_4];

The same is true for all the residence types.

**Comment by agrignard** [comment]
ok I see, 

When do you use this parameter? As a developer or as a user?

Those parameters are set only at the beginning of the experiment? Is it something that the final user with play with?

**Comment by doorleyr** [comment]
I'm using them this way just for prototyping. Ultimately, for a CityScope deployment, the same information would have to come from the user interactions (lego or some other input).

**Comment by agrignard** [comment]
Closing also this outdated issue
