### ISSUE TITLE
Treatment of Access Token

### ISSUE THREAD

**Issue by yshimbo** [CityScope/CS_Mobility_Service#9]
I found mapbox access token in js/deck/index.html.
I think it is better to use .env file to set the token.  (easy to operate and secure)

Thank you for your cool repository.
I study your  activity from Japan!

**Comment by doorleyr** [comment]
Thanks @yshimbo. This is solved in 97691b7 using gitignore

**Comment by RELNO** [comment]
@doorleyr just a note on that: mapbox made it easy to define 'scopes' for tokens (i.e domains in which token work, others not). https://docs.mapbox.com/help/account/tokens/
